# Generated by Django 2.2.13 on 2020-06-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
